=== caiosantosho2-dotcom/retail-bi-dashboard/contracts/lab_roc.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "lab_roc.json",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "grao",
    "dimensoes",
    "colunas",
    "linhas"
  ],
  "properties": {
    "grao": {
      "type": "string",
      "minLength": 1
    },
    "dimensoes": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "classificador"
      ],
      "properties": {
        "classificador": {
          "type": "array",
          "items": {
            "enum": [
              "modelo",
              "regra_simples"
            ]
          }
        }
      }
    },
    "colunas": {
      "const": [
        "classificador",
        "ponto",
        "fpr",
        "tpr",
        "corte"
      ]
    },
    "linhas": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "array",
        "prefixItems": [
          {
            "type": "integer",
            "minimum": 0
          },
          {
            "type": "integer",
            "minimum": 0
          },
          {
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          {
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          {
            "type": [
              "number",
              "null"
            ]
          }
        ],
        "minItems": 5,
        "maxItems": 5
      }
    }
  }
}

=== caiosantosho2-dotcom/retail-bi-dashboard/site/data/lab_roc.json
{"grao":"1 linha por classificador × ponto da curva ROC no conjunto de teste do RAG","dimensoes":{"classificador":["modelo","regra_simples"]},"colunas":["classificador","ponto","fpr","tpr","corte"],"linhas":[[0,0,0.0,0.0,null],[0,1,0.000241,0.0,0.6277926511942783],[0,2,0.000724,0.0,0.6070845450262106],[0,3,0.000724,0.010601,0.5820479116101834],[0,4,0.001449,0.010601,0.5768276585191319],[0,5,0.001449,0.021201,0.5644927200965423],[0,6,0.002173,0.021201,0.5608079065936681],[0,7,0.002173,0.024735,0.559803613785498],[0,8,0.002656,0.024735,0.5545474638244305],[0,9,0.002656,0.031802,0.5535219070421713],[0,10,0.002897,0.031802,0.5527410327217357],[0,11,0.002897,0.038869,0.5491285963175532],[0,12,0.00338,0.038869,0.5435641599699365],[0,13,0.00338,0.042403,0.5390544038864595],[0,14,0.003621,0.042403,0.536175878278411],[0,15,0.003621,0.045936,0.5346781615145805],[0,16,0.003863,0.045936,0.5344603964533222],[0,17,0.003863,0.04947,0.5311762900382136],[0,18,0.004104,0.04947,0.5231980492503825],[0,19,0.004104,0.056537,0.5192141921463027],[0,20,0.004829,0.056537,0.4971000307681261],[0,21,0.004829,0.060071,0.49469214242349263],[0,22,0.005311,0.060071,0.49304992935394704],[0,23,0.005311,0.063604,0.4924047274970335],[0,24,0.005553,0.063604,0.4917072586276957],[0,25,0.005553,0.067138,0.49009451501701273],[0,26,0.00676,0.067138,0.47718152774381833],[0,27,0.00676,0.070671,0.4744696754728435],[0,28,0.007726,0.070671,0.4597043975525247],[0,29,0.007726,0.074205,0.457237456953553],[0,30,0.008209,0.074205,0.45354402222528817],[0,31,0.008209,0.084806,0.44535779930750774],[0,32,0.008691,0.084806,0.43933663958189034],[0,33,0.008691,0.088339,0.4389222984994336],[0,34,0.008933,0.088339,0.4380653092320938],[0,35,0.008933,0.091873,0.43735053473841823],[0,36,0.009416,0.091873,0.43571175175439186],[0,37,0.009416,0.102473,0.43423439179061807],[0,38,0.009657,0.102473,0.4331367290205748],[0,39,0.009657,0.106007,0.4272171603140359],[0,40,0.012071,0.106007,0.41883207172539444],[0,41,0.012071,0.109541,0.41825182977912784],[0,42,0.013037,0.109541,0.4044037961018784],[0,43,0.013037,0.113074,0.40276289803837984],[0,44,0.013279,0.113074,0.40228595125797256],[0,45,0.013279,0.120141,0.40111969508711187],[0,46,0.014003,0.120141,0.3974421857662717],[0,47,0.014003,0.127208,0.3923053908073809],[0,48,0.014727,0.127208,0.38969161521924733],[0,49,0.014727,0.130742,0.38858968165658675],[0,50,0.014969,0.130742,0.3874446474043408],[0,51,0.014969,0.134276,0.3869485579195347],[0,52,0.015451,0.134276,0.38589527293147735],[0,53,0.015451,0.137809,0.3853199030666063],[0,54,0.015693,0.137809,0.3848299774304237],[0,55,0.015693,0.155477,0.37628315524243433],[0,56,0.016417,0.155477,0.37489003380237285],[0,57,0.016417,0.159011,0.37462825733578775],[0,58,0.017141,0.159011,0.37100113872248247],[0,59,0.017141,0.162544,0.3669824583348573],[0,60,0.019073,0.162544,0.3608948856985621],[0,61,0.019073,0.166078,0.36019951909481],[0,62,0.019314,0.166078,0.3598659299750856],[0,63,0.019314,0.169611,0.3593849836380098],[0,64,0.019797,0.169611,0.3552829840159413],[0,65,0.019797,0.173145,0.3550950067652201],[0,66,0.020521,0.173145,0.3502078987821698],[0,67,0.020521,0.176678,0.34997890697976825],[0,68,0.020763,0.176678,0.3483259828908875],[0,69,0.020763,0.180212,0.345237350301346],[0,70,0.022453,0.180212,0.340917386639832],[0,71,0.022453,0.183746,0.3386105128551609],[0,72,0.024143,0.183746,0.335368294134415],[0,73,0.024143,0.187279,0.3337336491562839],[0,74,0.024384,0.187279,0.3319785125821837],[0,75,0.024384,0.190813,0.3311383784833911],[0,76,0.024626,0.190813,0.330362961293158],[0,77,0.024626,0.194346,0.3283628086001624],[0,78,0.026799,0.194346,0.3221253722684947],[0,79,0.026799,0.19788,0.3206743787475315],[0,80,0.02704,0.19788,0.320238796066393],[0,81,0.02704,0.204947,0.3186145029854468],[0,82,0.02873,0.204947,0.3115679086710859],[0,83,0.02873,0.212014,0.309675569313555],[0,84,0.029213,0.212014,0.3083332924838734],[0,85,0.029213,0.219081,0.3070874336128244],[0,86,0.029454,0.219081,0.3068590839587162],[0,87,0.029454,0.222615,0.3068560398511372],[0,88,0.030662,0.222615,0.3024147704812641],[0,89,0.030662,0.226148,0.3020708146403813],[0,90,0.033076,0.226148,0.2978269924463003],[0,91,0.033076,0.229682,0.29703099379169073],[0,92,0.033559,0.229682,0.2967834661552683],[0,93,0.033559,0.233216,0.29644658861638906],[0,94,0.034042,0.233216,0.2955957020017287],[0,95,0.034042,0.236749,0.29477867145597514],[0,96,0.034283,0.236749,0.2947488723110353],[0,97,0.034283,0.240283,0.29454760905705174],[0,98,0.035732,0.240283,0.2894742646333424],[0,99,0.035732,0.24735,0.28852978102870325],[0,100,0.035973,0.24735,0.28837433631321313],[0,101,0.035973,0.254417,0.28819601665142563],[0,102,0.036214,0.254417,0.2877459986241654],[0,103,0.036214,0.257951,0.2870393195294943],[0,104,0.03718,0.257951,0.28326399188517787],[0,105,0.03718,0.261484,0.28273437394641554],[0,106,0.037904,0.261484,0.2808107113333203],[0,107,0.037904,0.265018,0.2801476757688288],[0,108,0.038146,0.265018,0.28005086304005133],[0,109,0.038146,0.272085,0.27930884688992735],[0,110,0.03887,0.272085,0.2775248798507503],[0,111,0.03887,0.275618,0.2767068684013967],[0,112,0.041284,0.275618,0.26894932641328717],[0,113,0.041284,0.279152,0.2685988323467281],[0,114,0.041767,0.279152,0.26761012636373654],[0,115,0.041767,0.282686,0.2674022014311197],[0,116,0.042009,0.282686,0.26684863541611004],[0,117,0.042009,0.286219,0.2663533851689911],[0,118,0.042974,0.286219,0.2605851838346758],[0,119,0.042974,0.289753,0.26041311052370936],[0,120,0.04732,0.289753,0.24828168981824061],[0,121,0.04732,0.293286,0.24798934412590276],[0,122,0.048286,0.293286,0.24456676564191068],[0,123,0.048286,0.300353,0.24369372273443451],[0,124,0.049493,0.300353,0.24194682577341428],[0,125,0.049493,0.30742,0.24076315158087375],[0,126,0.050217,0.30742,0.23878428003737756],[0,127,0.050217,0.310954,0.23797349130548962],[0,128,0.0507,0.310954,0.2376458439578589],[0,129,0.0507,0.318021,0.23610223924997187],[0,130,0.051424,0.318021,0.23333731707913075],[0,131,0.051424,0.321555,0.23264068323361753],[0,132,0.051907,0.321555,0.23225074358121348],[0,133,0.051907,0.335689,0.23063597240157094],[0,134,0.053356,0.335689,0.22903408866174646],[0,135,0.053356,0.34629,0.2278844851509636],[0,136,0.053839,0.34629,0.22737930814861207],[0,137,0.053839,0.349823,0.22470694013759615],[0,138,0.05408,0.349823,0.22394090842030642],[0,139,0.05408,0.35689,0.2234098042256446],[0,140,0.055287,0.35689,0.2199303661468908],[0,141,0.055287,0.360424,0.2198503688289287],[0,142,0.05577,0.360424,0.21939794421431813],[0,143,0.05577,0.363958,0.21865977146511667],[0,144,0.056494,0.363958,0.21614196184548476],[0,145,0.056494,0.367491,0.21561245015302136],[0,146,0.058184,0.367491,0.2121040210683678],[0,147,0.058184,0.378092,0.2110233511916361],[0,148,0.05915,0.378092,0.20975885865508465],[0,149,0.05915,0.381625,0.20941346168593827],[0,150,0.059874,0.381625,0.20914862966423264],[0,151,0.059874,0.385159,0.2091361125272753],[0,152,0.060357,0.385159,0.20840230005036292],[0,153,0.060357,0.388693,0.2080705296238627],[0,154,0.061082,0.388693,0.20646100965356973],[0,155,0.061082,0.392226,0.20586796333326268],[0,156,0.061323,0.392226,0.20561487775705786],[0,157,0.061323,0.39576,0.20546712919737026],[0,158,0.061806,0.39576,0.20529890202153656],[0,159,0.061806,0.399293,0.20479611467384098],[0,160,0.062289,0.399293,0.20372656248379425],[0,161,0.062289,0.402827,0.20336473414601705],[0,162,0.063979,0.402827,0.2015593750907668],[0,163,0.063979,0.40636,0.20135255789025033],[0,164,0.064462,0.40636,0.20112813103964833],[0,165,0.064462,0.409894,0.20065996806765432],[0,166,0.064944,0.409894,0.19931664311918587],[0,167,0.064944,0.413428,0.19915532833326866],[0,168,0.065669,0.413428,0.19892177875793232],[0,169,0.065669,0.416961,0.19864656151297802],[0,170,0.068807,0.416961,0.19480342533929065],[0,171,0.068807,0.427562,0.19343373682450954],[0,172,0.06929,0.427562,0.19270648877354113],[0,173,0.06929,0.431095,0.19189186677111075],[0,174,0.070014,0.431095,0.19092196548283394],[0,175,0.070014,0.438163,0.1894002169005492],[0,176,0.070497,0.438163,0.18913454187473852],[0,177,0.070497,0.441696,0.18897127594407676],[0,178,0.071222,0.441696,0.1881146681642727],[0,179,0.071222,0.44523,0.18765927771491933],[0,180,0.071463,0.44523,0.18751036622902142],[0,181,0.071463,0.448763,0.18737382632721147],[0,182,0.071704,0.448763,0.18635367529476726],[0,183,0.071704,0.452297,0.1860621680729718],[0,184,0.073636,0.452297,0.1829075852427964],[0,185,0.073636,0.45583,0.18269955888090914],[0,186,0.07436,0.45583,0.18200308763920922],[0,187,0.07436,0.459364,0.18188398005544812],[0,188,0.074602,0.459364,0.18129023317303075],[0,189,0.074602,0.462898,0.18109431401001586],[0,190,0.077257,0.462898,0.17881234121819634],[0,191,0.077257,0.466431,0.1782955975178636],[0,192,0.078947,0.466431,0.17635891304288215],[0,193,0.078947,0.473498,0.175510991352138],[0,194,0.07943,0.473498,0.17507794075008443],[0,195,0.07943,0.477032,0.17482375774386424],[0,196,0.080396,0.477032,0.17331940185666456],[0,197,0.080396,0.480565,0.1731239144822807],[0,198,0.081362,0.480565,0.17164368063718574],[0,199,0.081362,0.487633,0.16928419174654538],[0,200,0.082569,0.487633,0.16811368379288813],[0,201,0.082569,0.4947,0.16784209907897438],[0,202,0.083535,0.4947,0.16676652358975566],[0,203,0.083535,0.498233,0.16625350164957445],[0,204,0.083776,0.498233,0.16592147857669384],[0,205,0.083776,0.5053,0.16564803100742245],[0,206,0.0845,0.5053,0.16500351078751074],[0,207,0.0845,0.508834,0.16443164137929225],[0,208,0.084983,0.508834,0.16379420680463921],[0,209,0.084983,0.512367,0.16352958112274643],[0,210,0.085707,0.512367,0.1627701562559513],[0,211,0.085707,0.515901,0.1624873002942119],[0,212,0.086432,0.515901,0.16202154060852925],[0,213,0.086432,0.519435,0.16187411828161094],[0,214,0.08788,0.519435,0.16123355408637183],[0,215,0.08788,0.522968,0.16116570158053078],[0,216,0.088363,0.522968,0.16025110925836716],[0,217,0.088363,0.526502,0.15995247199851245],[0,218,0.090295,0.526502,0.1585396787345053],[0,219,0.090295,0.530035,0.1584373588993
